### ISSUE TITLE
Database configuration, Table and field definition, Database migration and maintenance

### ISSUE THREAD

**Issue by Kronos-orm** [Kronos-orm/Kronos-orm#1]

**Comment by Kronos-orm** [comment]
```kotlin
val ds = Kronos.dataSource

data class User(): KPojo

// 1.  return if the table exists
ds.table.exist<User>() // return Kotlin.Boolean
// 2. create a table
ds.table.create<User>()
// 3. confirm to delete a table
ds.table.delete<User>().confirm()
// 4. confirm to sync the structure from kotlin code to database
ds.table.structureSync<User>().confirm()
```

@Viggon1

**Comment by Viggon1** [comment]
> ```kotlin
> val ds = Kronos.dataSource
> 
> data class User(): KPojo
> 
> // 1.  return if the table exists
> ds.table.exist<User>() // return Kotlin.Boolean
> // 2. create a table
> ds.table.create<User>()
> // 3. confirm to delete a table
> ds.table.delete<User>().confirm()
> // 4. confirm to sync the structure from kotlin code to database
> ds.table.structureSync<User>().confirm()
> ```
> 
> @Viggon1

Ok I will create a PR to implement this feature

**Comment by Kronos-orm** [comment]
We need @Default() for column definition
