### ISSUE TITLE
Adjust the gradle project structure and configuration to remove the use of mavenLocal in gradle

### ISSUE THREAD

**Issue by ousc** [Kronos-orm/Kronos-orm#36]
In the current project structure, the following modules are mainly included:
1. `buildSrc` defines a general  maven publish function for submodule publish
2. `kronos-core`, `kronos-jvm-wrapper`, `kronos-logging` are the core of the project, written in pure kotlin
3. `kronos-compiler-plugin`, a compiler plugin for kotlin, provides expression tree parsing functions, and the test source code part depends on `kronos-core`, `kronos-jvm-wrapper`, `kronos-logging`
4. `kronos-maven-plugin`, `kronos-gradle-plugin`, build plugins, currently depend on `kronos-compiler-plugin` in the form of `api(project(":kronos-compiler-plugin"))`
5. kronos-testing needs to enable the `kronos-gradle-plugin` plugin, and the test needs to depend on other sub-modules such as `kronos-core`, `kronos-jvm-wrapper`, and `kronos-logging`.

Currently, when running this project for the first time, you need to first turn off the `kronos-gradle-plugin` plugin in `kronos-testing`, then publish `kronos-gradle-plugin` to `mavenLocal`, and finally turn on the plugin in `kronos-testing` (reads the Gradle plugin from mavenLocal) and start it. Is there any way to avoid and improve this process and avoid using mavenLocal?

@clovis-ai

**Comment by CLOVIS-AI** [comment]
Hey! The dependency from `kronos-gradle-plugin` to `kronos-compiler-plugin` isn't necessary. The Kotlin plugin adds it automatically based on the provided artifactId etc.
